"""Demo resource definitions for DemoBuilder-v2.

Each table below declares one family of LaunchDarkly resources created for
the demo environment.  To add or change a resource, edit the relevant table —
DemoBuilder-v2.py contains the generic creation loops that consume them.

Tables:
    METRICS         -> LDPlatform.create_metric(**spec)
    METRIC_GROUPS   -> LDPlatform.create_metric_group(**spec)
    FLAGS           -> create_flag(**spec["flag"]) + optional "post" follow-up calls
    SEGMENTS        -> created per environment listed, with shared rules
    CONTEXT_KINDS   -> [context_key, for_experiment]
    EXPERIMENTS     -> toggled flag, metrics, create_experiment kwargs
    PIPELINE_FLAGS  -> release-pipeline additions, metric attachments, phase advances

Entries with {"custom": "<method name>"} defer to a hand-written method on
DemoBuilder for cases that don't fit the generic shape.
"""

# ==========================================================================
# Resource definition tables
# ==========================================================================

# Metrics — passed straight to LDPlatform.create_metric(**spec)
METRICS = [
    {'metric_key': 'ai-chatbot-positive-feedback',
     'metric_name': 'AI Chatbot Positive Feedback',
     'event_key': 'ai-chatbot-positive-feedback',
     'metric_description': 'This metric will track positive feedback given to AI Model used in '
                           'chatbot for the good responses provided.',
     'success_criteria': 'HigherThanBaseline',
     'tags': ['experiment']},
    {'metric_key': 'ai-chatbot-negative-feedback',
     'metric_name': 'AI Chatbot Negative Feedback',
     'event_key': 'ai-chatbot-negative-feedback',
     'metric_description': 'This metric will track negative feedback given to AI Model used in '
                           'chatbot for the bad responses provided.',
     'success_criteria': 'LowerThanBaseline',
     'tags': ['experiment']},
    {'metric_key': 'ai-accuracy',
     'metric_name': 'AI Response Accuracy',
     'event_key': 'ai-accuracy',
     'metric_description': 'This metric will track the factual accuracy of AI responses as '
                           'evaluated by the LLM judge.',
     'numeric': True,
     'unit': '%',
     'success_criteria': 'HigherThanBaseline',
     'tags': ['experiment', 'ai-metrics']},
    {'metric_key': 'ai-source-fidelity',
     'metric_name': 'AI Source Fidelity',
     'event_key': 'ai-source-fidelity',
     'metric_description': 'This metric will track how well AI responses adhere to source material '
                           'and factual grounding.',
     'numeric': True,
     'unit': '%',
     'success_criteria': 'HigherThanBaseline',
     'tags': ['experiment', 'ai-metrics']},
    {'metric_key': 'ai-relevance',
     'metric_name': 'AI Response Relevance',
     'event_key': 'ai-relevance',
     'metric_description': "This metric will track how relevant AI responses are to the user's "
                           'query.',
     'numeric': True,
     'unit': '%',
     'success_criteria': 'HigherThanBaseline',
     'tags': ['experiment', 'ai-metrics']},
    {'metric_key': 'ai-cost',
     'metric_name': 'AI Response Cost',
     'event_key': 'ai-cost',
     'metric_description': 'This metric will track the cost per AI response based on token usage '
                           'and model pricing.',
     'numeric': True,
     'unit': '$',
     'success_criteria': 'LowerThanBaseline',
     'tags': ['experiment', 'ai-metrics']},
    {'metric_key': 'financial-agent-accuracy',
     'metric_name': 'Financial Agent Accuracy',
     'event_key': 'financial-agent-accuracy',
     'metric_description': 'This metric will track the accuracy of financial advice provided by '
                           'the Financial Advisor Agent.',
     'numeric': True,
     'unit': '%',
     'success_criteria': 'HigherThanBaseline',
     'tags': ['experiment', 'ai-metrics', 'financial-advisor']},
    {'metric_key': 'financial-agent-negative-feedback',
     'metric_name': 'Financial Agent Negative Feedback',
     'event_key': 'financial-agent-negative-feedback',
     'metric_description': 'This metric will track negative feedback given to the Financial '
                           'Advisor Agent for poor financial advice.',
     'success_criteria': 'LowerThanBaseline',
     'tags': ['experiment', 'ai-metrics', 'financial-advisor']},
    {'metric_key': 'in-cart-total-price',
     'metric_name': 'In-Cart Total Price',
     'event_key': 'in-cart-total-price',
     'metric_description': 'This metric will track the total price of items in the cart.',
     'numeric': True,
     'unit': '$',
     'success_criteria': 'HigherThanBaseline',
     'tags': ['experiment']},
    {'metric_key': 'in-cart-total-items',
     'metric_name': 'In-Cart Total Items',
     'event_key': 'in-cart-total-items',
     'metric_description': 'This metric will track the number of up-sell items in the cart.',
     'numeric': False,
     'unit': '',
     'success_criteria': 'HigherThanBaseline',
     'tags': ['experiment']},
    {'metric_key': 'recent-trades-db-errors',
     'metric_name': 'Database Error Rates',
     'event_key': 'recent-trades-db-errors',
     'metric_description': 'This metric will track the error rates in the database',
     'numeric': False,
     'unit': '',
     'success_criteria': 'LowerThanBaseline',
     'tags': ['experiment']},
    {'metric_key': 'recent-trades-db-latency',
     'metric_name': 'Database Latency',
     'event_key': 'recent-trades-db-latency',
     'metric_description': 'This metric will track the latency in the database',
     'numeric': True,
     'unit': 'ms',
     'success_criteria': 'LowerThanBaseline',
     'tags': ['experiment']},
    {'metric_key': 'stocks-api-error-rates',
     'metric_name': 'API Error Rates',
     'event_key': 'stocks-api-error-rates',
     'metric_description': 'This metric will track the error rates in the API',
     'numeric': False,
     'unit': '',
     'success_criteria': 'LowerThanBaseline',
     'tags': ['experiment']},
    {'metric_key': 'stocks-api-latency',
     'metric_name': 'API Latency',
     'event_key': 'stocks-api-latency',
     'metric_description': 'This metric will track the latency in the API',
     'numeric': True,
     'unit': 'ms',
     'success_criteria': 'LowerThanBaseline',
     'tags': ['experiment']},
    {'metric_key': 'store-accessed',
     'metric_name': 'Store Accessed',
     'event_key': 'store-accessed',
     'metric_description': 'This metric will track the number of times the store is accessed',
     'numeric': False,
     'unit': '',
     'success_criteria': 'HigherThanBaseline',
     'tags': ['experiment']},
    {'metric_key': 'item-added',
     'metric_name': 'Items Added to Cart',
     'event_key': 'item-added',
     'metric_description': 'This metric will track the number of items added to the cart',
     'numeric': False,
     'unit': '',
     'success_criteria': 'HigherThanBaseline',
     'tags': ['experiment']},
    {'metric_key': 'cart-accessed',
     'metric_name': 'Store Cart Accessed',
     'event_key': 'cart-accessed',
     'metric_description': 'This metric will track the number of times the cart is accessed',
     'numeric': False,
     'unit': '',
     'success_criteria': 'HigherThanBaseline',
     'tags': ['experiment']},
    {'metric_key': 'customer-checkout',
     'metric_name': 'Store Checkout Completed',
     'event_key': 'customer-checkout',
     'metric_description': 'This metric will track the number of times the store checkout is '
                           'completed',
     'numeric': False,
     'unit': '',
     'success_criteria': 'HigherThanBaseline',
     'tags': ['experiment']},
    {'metric_key': 'search-engine-add-to-cart',
     'metric_name': 'New Search Engine Add To Cart is Clicked',
     'event_key': 'search-engine-add-to-cart',
     'metric_description': 'This metric will track the number of times the new add to cart button '
                           'within the new search engine is clicked.',
     'numeric': False,
     'unit': '',
     'success_criteria': 'HigherThanBaseline',
     'randomization_units': ['user'],
     'tags': ['experiment']},
    {'metric_key': 'signup-clicked',
     'metric_name': 'Signup Click in Home Page - Public Sector',
     'event_key': 'signup clicked',
     'metric_description': 'This metric will track signup button clicks on the government home '
                           'page for the Public Sector demo.',
     'numeric': False,
     'unit': '',
     'success_criteria': 'HigherThanBaseline',
     'randomization_units': ['user'],
     'tags': ['public-sector']},
    {'metric_key': 'signup-started',
     'metric_name': 'ToggleBank Signup Started',
     'event_key': 'signup-started',
     'metric_description': 'This metric tracks when users click Join Now to start the signup '
                           'process in ToggleBank.',
     'numeric': False,
     'unit': '',
     'success_criteria': 'HigherThanBaseline',
     'randomization_units': ['user'],
     'tags': ['bank', 'signup-funnel']},
    {'metric_key': 'initial-signup-completed',
     'metric_name': 'ToggleBank Initial Signup Completed',
     'event_key': 'initial-signup-completed',
     'metric_description': 'This metric tracks when users complete the first signup step '
                           '(email/password) in ToggleBank.',
     'numeric': False,
     'unit': '',
     'success_criteria': 'HigherThanBaseline',
     'randomization_units': ['user'],
     'tags': ['bank', 'signup-funnel']},
    {'metric_key': 'signup-personal-details-completed',
     'metric_name': 'ToggleBank Personal Details Completed',
     'event_key': 'signup-personal-details-completed',
     'metric_description': 'This metric tracks when users complete the personal details step in '
                           'ToggleBank signup.',
     'numeric': False,
     'unit': '',
     'success_criteria': 'HigherThanBaseline',
     'randomization_units': ['user'],
     'tags': ['bank', 'signup-funnel']},
    {'metric_key': 'signup-services-completed',
     'metric_name': 'ToggleBank Services Selection Completed',
     'event_key': 'signup-services-completed',
     'metric_description': 'This metric tracks when users complete the services selection step in '
                           'ToggleBank signup.',
     'numeric': False,
     'unit': '',
     'success_criteria': 'HigherThanBaseline',
     'randomization_units': ['user'],
     'tags': ['bank', 'signup-funnel']},
    {'metric_key': 'signup-flow-completed',
     'metric_name': 'ToggleBank Full Signup Flow Completed',
     'event_key': 'signup-flow-completed',
     'metric_description': 'This metric tracks when users complete the entire ToggleBank signup '
                           'flow and are logged in.',
     'numeric': False,
     'unit': '',
     'success_criteria': 'HigherThanBaseline',
     'randomization_units': ['user'],
     'tags': ['bank', 'signup-funnel']},
    {'metric_key': 'rm-db-latency',
     'metric_name': 'Risk Management Database Latency - Public Sector',
     'event_key': 'rm-db-latency',
     'metric_description': 'This metric will track database latency for the Risk Management '
                           'Database in the Public Sector demo.',
     'numeric': True,
     'unit': 'ms',
     'success_criteria': 'LowerThanBaseline',
     'randomization_units': ['user'],
     'tags': ['guarded-release', 'public-sector']},
    {'metric_key': 'rm-db-errors',
     'metric_name': 'Risk Management Database Errors - Public Sector',
     'event_key': 'rm-db-errors',
     'metric_description': 'This metric will track database errors for the Risk Management '
                           'Database in the Public Sector demo.',
     'numeric': True,
     'unit': 'errors',
     'success_criteria': 'LowerThanBaseline',
     'randomization_units': ['user'],
     'tags': ['guarded-release', 'public-sector']},
    {'metric_key': 'rm-api-latency',
     'metric_name': 'Risk Management API Latency - Public Sector',
     'event_key': 'rm-api-latency',
     'metric_description': 'This metric will track API latency for the Risk Management API in the '
                           'Public Sector demo.',
     'numeric': True,
     'unit': 'ms',
     'success_criteria': 'LowerThanBaseline',
     'randomization_units': ['user'],
     'tags': ['guarded-release', 'public-sector']},
    {'metric_key': 'rm-api-errors',
     'metric_name': 'Risk Management API Errors - Public Sector',
     'event_key': 'rm-api-errors',
     'metric_description': 'This metric will track API errors for the Risk Management API in the '
                           'Public Sector demo.',
     'numeric': False,
     'unit': '',
     'success_criteria': 'LowerThanBaseline',
     'tags': ['guarded-release', 'public-sector']},
    {'metric_key': 'payment-success-rate',
     'metric_name': 'Payment Success Rate - ToggleBank',
     'event_key': 'payment-success-rate',
     'metric_description': 'Tracks successful payment transactions in the payment engine upgrade.',
     'numeric': False,
     'unit': '',
     'success_criteria': 'HigherThanBaseline',
     'tags': ['guarded-release', 'bank', 'payment']},
    {'metric_key': 'payment-latency',
     'metric_name': 'Payment Latency - ToggleBank',
     'event_key': 'payment-latency',
     'metric_description': 'Tracks payment processing latency in milliseconds for the payment '
                           'engine upgrade.',
     'numeric': True,
     'unit': 'ms',
     'success_criteria': 'LowerThanBaseline',
     'tags': ['guarded-release', 'bank', 'payment']},
    {'metric_key': 'payment-error-rate',
     'metric_name': 'Payment Error Rate - ToggleBank',
     'event_key': 'payment-error-rate',
     'metric_description': 'Tracks payment processing errors in the payment engine upgrade.',
     'numeric': False,
     'unit': '',
     'success_criteria': 'LowerThanBaseline',
     'tags': ['guarded-release', 'bank', 'payment']},
    {'metric_key': 'payment-v2-success-rate',
     'metric_name': 'Payment v2 Success Rate - ToggleBank',
     'event_key': 'payment-v2-success-rate',
     'metric_description': 'Tracks successful payment transactions in the payment processing v2.0 '
                           'system.',
     'numeric': True,
     'unit': 'pp',
     'success_criteria': 'HigherThanBaseline',
     'tags': ['guarded-release', 'bank', 'payment']},
    {'metric_key': 'payment-v2-latency',
     'metric_name': 'Payment v2 Latency - ToggleBank',
     'event_key': 'payment-v2-latency',
     'metric_description': 'Tracks payment processing latency in milliseconds for the payment '
                           'processing v2.0 system.',
     'numeric': True,
     'unit': 'ms',
     'success_criteria': 'LowerThanBaseline',
     'tags': ['guarded-release', 'bank', 'payment']},
    {'metric_key': 'payment-v2-error-rate',
     'metric_name': 'Payment v2 Error Rate - ToggleBank',
     'event_key': 'payment-v2-error-rate',
     'metric_description': 'Tracks payment processing errors in the payment processing v2.0 '
                           'system.',
     'numeric': True,
     'unit': 'pp',
     'success_criteria': 'LowerThanBaseline',
     'tags': ['guarded-release', 'bank', 'payment']},
    {'metric_key': 'payment-interactive-success-rate',
     'metric_name': 'Payment Interactive Demo Success Rate - ToggleBank',
     'event_key': 'payment-interactive-success-rate',
     'metric_description': 'Tracks successful payment transactions in the interactive demo system.',
     'numeric': False,
     'unit': '',
     'success_criteria': 'HigherThanBaseline',
     'tags': ['guarded-release', 'bank', 'payment', 'interactive-demo']},
    {'metric_key': 'payment-interactive-latency',
     'metric_name': 'Payment Interactive Demo Latency - ToggleBank',
     'event_key': 'payment-interactive-latency',
     'metric_description': 'Tracks payment processing latency in milliseconds for the interactive '
                           'demo system.',
     'numeric': True,
     'unit': 'ms',
     'success_criteria': 'LowerThanBaseline',
     'tags': ['guarded-release', 'bank', 'payment', 'interactive-demo']},
    {'metric_key': 'payment-interactive-error-rate',
     'metric_name': 'Payment Interactive Demo Error Rate - ToggleBank',
     'event_key': 'payment-interactive-error-rate',
     'metric_description': 'Tracks payment processing errors in the interactive demo system.',
     'numeric': False,
     'unit': '',
     'success_criteria': 'LowerThanBaseline',
     'tags': ['guarded-release', 'bank', 'payment', 'interactive-demo']},
    {'metric_key': 'payment-transactions-processed',
     'metric_name': 'Payment Transactions Processed - ToggleBank',
     'event_key': 'payment-transactions-processed',
     'metric_description': 'Tracks total number of payment transactions successfully processed.',
     'numeric': True,
     'unit': 'transactions',
     'success_criteria': 'HigherThanBaseline',
     'tags': ['guarded-release', 'bank', 'payment', 'business']},
    {'metric_key': 'payment-revenue-protected',
     'metric_name': 'Payment Revenue Protected - ToggleBank',
     'event_key': 'payment-revenue-protected',
     'metric_description': 'Tracks estimated revenue protected by automatic rollback during '
                           'payment engine failures.',
     'numeric': True,
     'unit': 'USD',
     'success_criteria': 'HigherThanBaseline',
     'tags': ['guarded-release', 'bank', 'payment', 'business']},
    {'metric_key': 'telemetry-error-metric',
     'metric_name': 'Telemetry Errors',
     'event_key': '$ld:telemetry:error',
     'metric_description': 'Tracks frontend errors captured by the Observability SDK for '
                           'regression debugging.',
     'numeric': False,
     'unit': '',
     'success_criteria': 'LowerThanBaseline',
     'tags': ['guarded-release', 'bank', 'observability', 'transaction-monitoring']},
]

# Metric groups — passed to create_metric_group(**spec)
METRIC_GROUPS = [
    {'group_key': 'store-purchases',
     'group_name': 'Store Purchases',
     'metrics': [{'key': 'store-accessed', 'nameInGroup': '1'},
                 {'key': 'item-added', 'nameInGroup': '2'},
                 {'key': 'cart-accessed', 'nameInGroup': '3'},
                 {'key': 'customer-checkout', 'nameInGroup': '4'}],
     'kind': 'funnel',
     'description': 'This metric group will track the store purchases'},
    {'group_key': 'shorten-collection-page-metric-group',
     'group_name': 'Shorten Collection Page Metric Group',
     'metrics': [{'key': 'item-added', 'nameInGroup': '1'},
                 {'key': 'cart-accessed', 'nameInGroup': '2'},
                 {'key': 'customer-checkout', 'nameInGroup': '3'}],
     'kind': 'funnel',
     'description': 'This metric group will track the store purchases relating to the new shorten '
                    'collection page.'},
    {'group_key': 'togglebank-signup-funnel',
     'group_name': 'ToggleBank Signup Funnel',
     'metrics': [{'key': 'signup-started', 'nameInGroup': '1'},
                 {'key': 'initial-signup-completed', 'nameInGroup': '2'},
                 {'key': 'signup-personal-details-completed', 'nameInGroup': '3'},
                 {'key': 'signup-services-completed', 'nameInGroup': '4'},
                 {'key': 'signup-flow-completed', 'nameInGroup': '5'}],
     'kind': 'funnel',
     'description': 'This metric group will track the ToggleBank signup funnel conversion flow.'},
]

# Feature flags. "flag" -> create_flag kwargs; optional "post" -> follow-up
# LDPlatform calls as [method, args, kwargs] (rollouts, metric attachments).
FLAGS = [
    {'flag': {'flag_key': 'wealthManagement',
              'flag_name': 'A1 - Release: Wealth Management Component',
              'description': 'Releasing new wealth management component on ToggleBank',
              'variations': [{'value': True, 'name': 'Release Wealth Management Component'},
                             {'value': False, 'name': 'Hide Wealth Management Component'}],
              'tags': ['release', 'bank'],
              'on_variation': 1}},
    {'flag': {'flag_key': 'enhancedNotificationCenter',
              'flag_name': 'A1.1 - Release: Enhanced Notification Center - ToggleBank',
              'description': 'Releases new enhanced notification center with real-time updates and '
                             'improved UI',
              'variations': [{'value': True, 'name': 'Enable Enhanced Notification Center'},
                             {'value': False, 'name': 'Use Legacy Notifications'}],
              'tags': ['release', 'bank', 'observability'],
              'on_variation': 1}},
    {'custom': 'flag_federated_account'},
    {'flag': {'flag_key': 'paymentEngineHealthyRollout',
              'flag_name': 'A3 - Release: Payment Engine Upgrade - Healthy Rollout - ToggleBank',
              'description': 'Releases upgraded payment engine with improved performance and '
                             'reliability. Demonstrates smooth deployment with healthy metrics.',
              'variations': [{'value': True, 'name': 'Show Healthy Rollout Scenario'},
                             {'value': False, 'name': 'Hide Scenario'}],
              'tags': ['guarded-release', 'bank', 'scenario'],
              'on_variation': 1},
     'post': [['attach_metric_to_flag',
               ['paymentEngineHealthyRollout',
                ['payment-success-rate',
                 'payment-latency',
                 'payment-error-rate',
                 'payment-transactions-processed']],
               {}],
              ['add_guarded_rollout',
               ['paymentEngineHealthyRollout', 'production'],
               {'metrics': ['payment-success-rate', 'payment-latency', 'payment-error-rate'],
                'days': 1}]]},
    {'custom': 'flag_payment_engine_failed_rollout'},
    {'flag': {'flag_key': 'paymentProcessingInteractiveDemo',
              'flag_name': 'A4.1 - Interactive Demo: Payment Processing - ToggleBank',
              'description': 'Interactive flag for live demos of guarded rollouts. Can be manually '
                             'configured for healthy OR failed scenarios during presentations.',
              'variations': [{'value': True, 'name': 'Enable New Payment Processing'},
                             {'value': False, 'name': 'Use Legacy Payment Processing'}],
              'tags': ['guarded-release', 'bank', 'demo', 'interactive'],
              'on_variation': 1},
     'post': [['attach_metric_to_flag',
               ['paymentProcessingInteractiveDemo',
                ['payment-interactive-success-rate',
                 'payment-interactive-latency',
                 'payment-interactive-error-rate',
                 'payment-transactions-processed',
                 'payment-revenue-protected',
                 '$ld:telemetry:error']],
               {}]]},
    {'flag': {'flag_key': 'showDifferentSpecialOfferString',
              'flag_name': 'A5 - Feature Experiment: Show Different Special Offer - ToggleBank',
              'description': 'This feature flag controls which special offer variant is displayed '
                             'on the ToggleBank home page',
              'variations': [{'value': 'offerA', 'name': 'offerA'},
                             {'value': 'offerB', 'name': 'offerB'},
                             {'value': 'offerC', 'name': 'offerC'}],
              'tags': ['Experimentation', 'bank'],
              'on_variation': 0,
              'off_variation': 1}},
    {'flag': {'flag_key': 'releaseNewSignupPromo',
              'flag_name': 'A6 - Funnel Experiment: New Signup Flow - ToggleBank',
              'description': 'This feature flag controls which promotional offer is displayed in '
                             'the marketing banner to test which offer drives the most signup '
                             'conversions',
              'variations': [{'value': 'creditCardOffer',
                              'name': 'Credit Card: 0% APR for 12 months'},
                             {'value': 'mortgageOffer', 'name': 'Mortgage: 0.50% off 30 year loan'},
                             {'value': 'cashbackOffer',
                              'name': 'Checking: $200 cashback when you spend $2500+'}],
              'tags': ['Experimentation', 'bank'],
              'on_variation': 0,
              'off_variation': 2}},
    {'flag': {'flag_key': 'swapWidgetPositions',
              'flag_name': 'A7 - Feature Experiment: Widget Position Swap - ToggleBank',
              'description': 'This feature flag controls whether the mortgage and retirement '
                             'widgets are swapped on the ToggleBank home page',
              'variations': [{'value': True, 'name': 'Retirement Left, Mortgage Right'},
                             {'value': False, 'name': 'Mortgage Left, Retirement Right'}],
              'tags': ['Experimentation', 'bank'],
              'on_variation': 0,
              'off_variation': 1}},
    {'flag': {'flag_key': 'transactionMonitoring',
              'flag_name': 'A8 - Release: Transaction Monitoring System - ToggleBank',
              'description': 'Demo flag for regression debug feature enabling real-time '
                             'transaction monitoring and observability insights.',
              'variations': [{'value': True, 'name': 'Enable Transaction Monitoring'},
                             {'value': False, 'name': 'Disable Transaction Monitoring'}],
              'tags': ['guarded-release', 'bank', 'observability'],
              'on_variation': 0},
     'post': [['add_guarded_rollout',
               ['transactionMonitoring', 'production'],
               {'metrics': ['telemetry-error-metric'], 'days': 1}]]},
    {'flag': {'flag_key': 'investment-recent-trade-db',
              'flag_name': 'B1 - Release: New Database (Guarded Release) - Investment',
              'description': 'Release new database for recent trading component',
              'variations': [{'value': True, 'name': 'Add New Database'},
                             {'value': False, 'name': 'Remove New Database'}],
              'tags': ['guarded-release', 'investment'],
              'on_variation': 1},
     'post': [['attach_metric_to_flag',
               ['investment-recent-trade-db',
                ['recent-trades-db-latency', 'recent-trades-db-errors']],
               {}],
              ['add_guarded_rollout', ['investment-recent-trade-db', 'production'], {'days': 1}]]},
    {'flag': {'flag_key': 'release-new-investment-stock-api',
              'flag_name': 'B2 - Release: New API (Guarded Release) - Investment',
              'description': 'Release new API for stocks component',
              'variations': [{'value': True, 'name': 'Release New API 2.0'},
                             {'value': False, 'name': 'Revert to Old API 1.0'}],
              'tags': ['guarded-release', 'investment'],
              'on_variation': 0},
     'post': [['attach_metric_to_flag',
               ['release-new-investment-stock-api',
                ['stocks-api-latency', 'stocks-api-error-rates']],
               {}],
              ['add_guarded_rollout',
               ['release-new-investment-stock-api', 'production'],
               {'days': 1}]]},
    {'flag': {'flag_key': 'cartSuggestedItems',
              'flag_name': 'D1 - Feature Experiment: Suggested Items Carousel',
              'description': 'Releasing New Suggested Items Carousel Component for the cart '
                             'component in Galaxy Marketplace',
              'variations': [{'value': True, 'name': 'New Suggested Items Carousel'},
                             {'value': False, 'name': 'Old Continue Shopping Button'}],
              'tags': ['experiment', 'ecommerce'],
              'on_variation': 0,
              'off_variation': 1}},
    {'flag': {'flag_key': 'storeAttentionCallout',
              'flag_name': 'D2 - Funnel Experiment: Promotion Banner',
              'description': 'Releasing New Collection Promotion Banner for the Galaxy Marketplace',
              'variations': [{'value': 'New Items', 'name': '(Control) New Items'},
                             {'value': 'Sale', 'name': 'Sale'},
                             {'value': 'Final Hours!', 'name': 'Final Hours!'}],
              'tags': ['experiment', 'ecommerce'],
              'on_variation': 0,
              'off_variation': 1}},
    {'flag': {'flag_key': 'release-new-search-engine',
              'flag_name': 'D3 - Feature Experiment: New Search Engine',
              'description': 'Release New Search Engine in Galaxy Marketplace',
              'variations': [{'value': True, 'name': 'New Search Engine'},
                             {'value': False, 'name': 'Old Search Engine'}],
              'tags': ['experiment', 'ecommerce'],
              'on_variation': 0,
              'off_variation': 1}},
    {'flag': {'flag_key': 'release-new-shorten-collections-page',
              'flag_name': 'D4 - Funnel Experiment: New Shorten Collection Pages',
              'description': 'Release New Shorten Collections Page in Galaxy Marketplace',
              'variations': [{'value': 'new-shorten-collections-page',
                              'name': 'New Shorten Collections Page'},
                             {'value': 'old-long-collections-page',
                              'name': 'Old Longer Collections Page'}],
              'tags': ['experiment', 'ecommerce'],
              'on_variation': 0,
              'off_variation': 1}},
    {'flag': {'flag_key': 'q-4-increase-average-total-in-cart-price-ld-holdout',
              'flag_name': 'Flag to Create Q4 Increase Total Price Holdout',
              'description': 'Description: Flag to create holdout for q4 increase incart price',
              'variations': [{'value': True, 'name': 'In holdout'},
                             {'value': False, 'name': 'Not In holdout'}],
              'purpose': 'holdout',
              'on_variation': 0,
              'off_variation': 1}},
    {'flag': {'flag_key': 'financialDBMigration',
              'flag_name': 'E1 - Migration: Database (Migration Tool)',
              'description': 'This feature flag will trigger the database migration tool in '
                             'LaunchAirways',
              'purpose': 'migration',
              'migration_stages': 6,
              'tags': ['release', 'migration-assistant', 'optional'],
              'temporary': True}},
    {'flag': {'flag_key': 'enhancedUserAuthentication',
              'flag_name': 'F1 - Enhanced User Authentication',
              'description': 'This feature flag will trigger the enhanced user authentication in '
                             'ToggleBank',
              'variations': [{'value': True, 'name': 'Enable Enhanced User Authentication'},
                             {'value': False, 'name': 'Disable Enhanced User Authentication'}],
              'tags': ['release', 'release-pipeline', 'utils'],
              'on_variation': 0,
              'off_variation': 1}},
    {'flag': {'flag_key': 'biometricLoginSupport',
              'flag_name': 'F2 - Biometric Login Support',
              'description': 'This feature flag will enable biometric login support in ToggleBank',
              'variations': [{'value': True, 'name': 'Enable Biometric Login'},
                             {'value': False, 'name': 'Disable Biometric Login'}],
              'tags': ['release', 'release-pipeline', 'utils'],
              'on_variation': 0,
              'off_variation': 1}},
    {'flag': {'flag_key': 'customizableAccountDashboards',
              'flag_name': 'F3 - Customizable Account Dashboards',
              'description': 'This feature flag will allow users to customize their account '
                             'dashboards in ToggleBank',
              'variations': [{'value': True, 'name': 'Enable Customizable Dashboards'},
                             {'value': False, 'name': 'Disable Customizable Dashboards'}],
              'tags': ['release', 'release-pipeline', 'utils'],
              'on_variation': 0,
              'off_variation': 1}},
    {'flag': {'flag_key': 'realTimeTransactionAlerts',
              'flag_name': 'F4 - Real-Time Transaction Alerts',
              'description': 'This feature flag will enable real-time transaction alerts in '
                             'ToggleBank',
              'variations': [{'value': True, 'name': 'Enable Real-Time Alerts'},
                             {'value': False, 'name': 'Disable Real-Time Alerts'}],
              'tags': ['release', 'release-pipeline', 'utils'],
              'on_variation': 0,
              'off_variation': 1}},
    {'flag': {'flag_key': 'aiPoweredExpenseCategorization',
              'flag_name': 'F5 - AI-Powered Expense Categorization',
              'description': 'This feature flag will enable AI-powered expense categorization in '
                             'ToggleBank',
              'variations': [{'value': True, 'name': 'Enable AI Expense Categorization'},
                             {'value': False, 'name': 'Disable AI Expense Categorization'}],
              'tags': ['release', 'release-pipeline', 'utils'],
              'on_variation': 0,
              'off_variation': 1}},
    {'flag': {'flag_key': 'fraudDetectionAlerts',
              'flag_name': 'F6 - Fraud Detection Alerts',
              'description': 'This feature flag will enable fraud detection alerts in ToggleBank',
              'variations': [{'value': True, 'name': 'Enable Fraud Detection Alerts'},
                             {'value': False, 'name': 'Disable Fraud Detection Alerts'}],
              'tags': ['release', 'release-pipeline', 'utils'],
              'on_variation': 0,
              'off_variation': 1}},
    {'flag': {'flag_key': 'darkModeInterfaceOption',
              'flag_name': 'F7 - Dark Mode Interface Option',
              'description': 'This feature flag will enable the dark mode interface option in '
                             'ToggleBank',
              'variations': [{'value': True, 'name': 'Enable Dark Mode'},
                             {'value': False, 'name': 'Disable Dark Mode'}],
              'tags': ['release', 'release-pipeline', 'utils'],
              'on_variation': 0,
              'off_variation': 1}},
    {'flag': {'flag_key': 'automatedSavingsGoals',
              'flag_name': 'F8 - Automated Savings Goals',
              'description': 'This feature flag will enable automated savings goals in ToggleBank',
              'variations': [{'value': True, 'name': 'Enable Automated Savings Goals'},
                             {'value': False, 'name': 'Disable Automated Savings Goals'}],
              'tags': ['release', 'release-pipeline', 'utils'],
              'on_variation': 0,
              'off_variation': 1}},
    {'flag': {'flag_key': 'multiCurrencySupport',
              'flag_name': 'F9 - Multi-Currency Support',
              'description': 'This feature flag will enable multi-currency support in ToggleBank',
              'variations': [{'value': True, 'name': 'Enable Multi-Currency Support'},
                             {'value': False, 'name': 'Disable Multi-Currency Support'}],
              'tags': ['release', 'release-pipeline', 'utils'],
              'on_variation': 0,
              'off_variation': 1}},
    {'flag': {'flag_key': 'peerToPeerPaymentTransfers',
              'flag_name': 'F10 - Peer-to-Peer Payment Transfers',
              'description': 'This feature flag will enable peer-to-peer payment transfers in '
                             'ToggleBank',
              'variations': [{'value': True, 'name': 'Enable Peer-to-Peer Payment Transfers'},
                             {'value': False, 'name': 'Disable Peer-to-Peer Payment Transfers'}],
              'tags': ['release', 'release-pipeline', 'utils'],
              'on_variation': 0,
              'off_variation': 1}},
    {'flag': {'flag_key': 'creditScoreMonitoringTool',
              'flag_name': 'F12 - Credit Score Monitoring Tool',
              'description': 'This feature flag will enable the credit score monitoring tool in '
                             'ToggleBank',
              'variations': [{'value': True, 'name': 'Enable Credit Score Monitoring Tool'},
                             {'value': False, 'name': 'Disable Credit Score Monitoring Tool'}],
              'tags': ['release', 'release-pipeline', 'utils'],
              'on_variation': 0,
              'off_variation': 1}},
    {'flag': {'flag_key': 'voiceCommandBankingAssistant',
              'flag_name': 'F13 - Voice Command Banking Assistant',
              'description': 'This feature flag will enable the voice command banking assistant in '
                             'ToggleBank',
              'variations': [{'value': True, 'name': 'Enable Voice Command Banking Assistant'},
                             {'value': False, 'name': 'Disable Voice Command Banking Assistant'}],
              'tags': ['release', 'release-pipeline', 'utils'],
              'on_variation': 0,
              'off_variation': 1}},
    {'flag': {'flag_key': 'loanApplicationTracker',
              'flag_name': 'F14 - Loan Application Tracker',
              'description': 'This feature flag will enable the loan application tracker in '
                             'ToggleBank',
              'variations': [{'value': True, 'name': 'Enable Loan Application Tracker'},
                             {'value': False, 'name': 'Disable Loan Application Tracker'}],
              'tags': ['release', 'release-pipeline', 'utils'],
              'on_variation': 0,
              'off_variation': 1}},
    {'flag': {'flag_key': 'detailedSpendingInsightsReports',
              'flag_name': 'F15 - Detailed Spending Insights & Reports',
              'description': 'This feature flag will enable detailed spending insights and reports '
                             'in ToggleBank',
              'variations': [{'value': True, 'name': 'Enable Detailed Spending Insights & Reports'},
                             {'value': False,
                              'name': 'Disable Detailed Spending Insights & Reports'}],
              'tags': ['release', 'release-pipeline', 'utils'],
              'on_variation': 0,
              'off_variation': 1}},
    {'flag': {'flag_key': 'scheduledBillPayments',
              'flag_name': 'F15 - Scheduled Bill Payments',
              'description': 'This feature flag will enable scheduled bill payments in ToggleBank',
              'variations': [{'value': True, 'name': 'Enable Scheduled Bill Payments'},
                             {'value': False, 'name': 'Disable Scheduled Bill Payments'}],
              'tags': ['release', 'release-pipeline', 'utils'],
              'on_variation': 0,
              'off_variation': 1}},
    {'flag': {'flag_key': 'crossBorderPaymentSimplification',
              'flag_name': 'F16 - Cross-Border Payment Simplification',
              'description': 'This feature flag will simplify cross-border payments in ToggleBank',
              'variations': [{'value': True, 'name': 'Enable Cross-Border Payment Simplification'},
                             {'value': False,
                              'name': 'Disable Cross-Border Payment Simplification'}],
              'tags': ['release', 'release-pipeline', 'utils'],
              'on_variation': 0,
              'off_variation': 1}},
    {'flag': {'flag_key': 'merchantRewardsIntegration',
              'flag_name': 'F17 - Merchant Rewards Integration',
              'description': 'This feature flag will enable merchant rewards integration in '
                             'ToggleBank',
              'variations': [{'value': True, 'name': 'Enable Merchant Rewards Integration'},
                             {'value': False, 'name': 'Disable Merchant Rewards Integration'}],
              'tags': ['release', 'release-pipeline', 'utils'],
              'on_variation': 0,
              'off_variation': 1}},
    {'flag': {'flag_key': 'virtualCardIssuance',
              'flag_name': 'F18 - Virtual Card Issuance',
              'description': 'This feature flag will enable virtual card issuance in ToggleBank',
              'variations': [{'value': True, 'name': 'Enable Virtual Card Issuance'},
                             {'value': False, 'name': 'Disable Virtual Card Issuance'}],
              'tags': ['release', 'release-pipeline', 'utils'],
              'on_variation': 0,
              'off_variation': 1}},
    {'flag': {'flag_key': 'apiSupportForThirdPartyApplications',
              'flag_name': 'F19 - API Support for Third-Party Applications',
              'description': 'This feature flag will enable API support for third-party '
                             'applications in ToggleBank',
              'variations': [{'value': True,
                              'name': 'Enable API Support for Third-Party Applications'},
                             {'value': False,
                              'name': 'Disable API Support for Third-Party Applications'}],
              'tags': ['release', 'release-pipeline', 'utils'],
              'on_variation': 0,
              'off_variation': 1}},
    {'flag': {'flag_key': 'showCardsSectionComponent',
              'flag_name': 'P1 - Release: Show Cards Section Component - Public Sector',
              'description': 'This feature flag controls the visibility of service cards on the '
                             'government demo page',
              'variations': [{'value': True, 'name': 'Show Card Section'},
                             {'value': False, 'name': 'Hide Card Section'}],
              'tags': ['public-sector', 'release'],
              'on_variation': 1}},
    {'flag': {'flag_key': 'patchShowCardsSectionComponent',
              'flag_name': 'P2 - Release: Patch Show Cards Section Component - Public Sector',
              'description': 'Controls patch behavior for the first news card in the government '
                             'cards section.',
              'variations': [{'value': True, 'name': 'Apply Patch'},
                             {'value': False, 'name': 'Not Apply Patch'}],
              'tags': ['public-sector', 'release'],
              'on_variation': 1}},
    {'flag': {'flag_key': 'showHeroRedesign',
              'flag_name': 'P3 - Feature Experiment: Show Hero Redesign - Public Sector',
              'description': 'This feature flag enables the hero redesign experiment for the '
                             'government demo page',
              'variations': [{'value': 'text-left', 'name': 'Show Text Left In Hero Component'},
                             {'value': 'text-right', 'name': 'Show Text Right In Hero Component'}],
              'tags': ['Experimentation', 'public-sector'],
              'on_variation': 0,
              'off_variation': 1}},
    {'flag': {'flag_key': 'showDifferentHeroImageString',
              'flag_name': 'P4 - Feature Experiment: Show Different Hero Image - Public Sector',
              'description': 'This feature flag controls which hero image variant is displayed on '
                             'the government demo page',
              'variations': [{'value': 'imageA', 'name': 'imageA'},
                             {'value': 'imageB', 'name': 'imageB'},
                             {'value': 'imageC', 'name': 'imageC'}],
              'tags': ['Experimentation', 'public-sector'],
              'on_variation': 0,
              'off_variation': 1}},
    {'flag': {'flag_key': 'riskmgmtbureauDBGuardedRelease',
              'flag_name': 'P5 - Release: Add New Database (Guarded Release) - Public Sector',
              'description': 'Release new Risk Management Database for Public Sector demo',
              'variations': [{'value': True, 'name': 'Added Risk Management Database'},
                             {'value': False, 'name': 'Removed Risk Management Database'}],
              'tags': ['guarded-release', 'public-sector'],
              'on_variation': 1},
     'post': [['add_guarded_rollout',
               ['riskmgmtbureauDBGuardedRelease', 'production'],
               {'metrics': ['rm-db-latency', 'rm-db-errors'], 'days': 1}]]},
    {'flag': {'flag_key': 'riskmgmtbureauAPIGuardedRelease',
              'flag_name': 'P6 - Release: API v2.0 (Guarded Release) - Public Sector',
              'description': 'Release new Risk Management API v2.0 for Public Sector demo',
              'variations': [{'value': True, 'name': 'Release Risk Management API v2.0'},
                             {'value': False, 'name': 'Rollback to Risk Management API v1.0'}],
              'tags': ['guarded-release', 'public-sector'],
              'on_variation': 0},
     'post': [['add_guarded_rollout',
               ['riskmgmtbureauAPIGuardedRelease', 'production'],
               {'metrics': ['rm-api-latency', 'rm-api-errors'], 'days': 1}]]},
    {'flag': {'flag_key': 'demoMode',
              'flag_name': 'X1 - Demo Mode (Demo Engineering Team Use Only)',
              'description': 'This feature flag is used to determine whether an environment is for '
                             'demo purposes for events',
              'variations': [{'value': True, 'name': 'Enable Demo Mode'},
                             {'value': False, 'name': 'Disable Demo Mode'}],
              'tags': ['demo', 'events', 'demoengineering'],
              'on_variation': 0,
              'off_variation': 1}},
    {'flag': {'flag_key': 'betaDarkMode',
              'flag_name': 'T1 - Beta: Dark Mode',
              'description': 'This feature flag will enable dark mode in ToggleBank',
              'variations': [{'value': True, 'name': 'Enable Dark Mode'},
                             {'value': False, 'name': 'Disable Dark Mode'}],
              'tags': ['temporary'],
              'on_variation': 0,
              'off_variation': 1,
              'temporary': True}},
    {'flag': {'flag_key': 'experimentalPaymentGateway',
              'flag_name': 'T2 - Experimental Payment Gateway',
              'description': 'This feature flag will enable experimental payment gateway in '
                             'ToggleBank',
              'variations': [{'value': True, 'name': 'Enable Experimental Payment Gateway'},
                             {'value': False, 'name': 'Disable Experimental Payment Gateway'}],
              'tags': ['temporary'],
              'on_variation': 0,
              'off_variation': 1,
              'temporary': True}},
    {'flag': {'flag_key': 'limitedTimeOfferBanner',
              'flag_name': 'T3 - Limited Time Offer Banner',
              'description': 'This feature flag will enable limited time offer banner in '
                             'ToggleBank',
              'variations': [{'value': True, 'name': 'Enable Limited Time Offer Banner'},
                             {'value': False, 'name': 'Disable Limited Time Offer Banner'}],
              'tags': ['temporary'],
              'on_variation': 0,
              'off_variation': 1,
              'temporary': True}},
    {'flag': {'flag_key': 'earlyAccessFeatureToggle',
              'flag_name': 'T4 - Early Access Feature Toggle',
              'description': 'This feature flag will enable early access feature toggle in '
                             'ToggleBank',
              'variations': [{'value': True, 'name': 'Enable Early Access Feature Toggle'},
                             {'value': False, 'name': 'Disable Early Access Feature Toggle'}],
              'tags': ['temporary'],
              'on_variation': 0,
              'off_variation': 1,
              'temporary': True}},
    {'flag': {'flag_key': 'debuggingModeForDevelopers',
              'flag_name': 'T5 - Debugging Mode for Developers',
              'description': 'This feature flag will enable debugging mode for developers in '
                             'ToggleBank',
              'variations': [{'value': True, 'name': 'Enable Debugging Mode for Developers'},
                             {'value': False, 'name': 'Disable Debugging Mode for Developers'}],
              'tags': ['temporary'],
              'on_variation': 0,
              'off_variation': 1,
              'temporary': True}},
]

# Segments — created in each listed environment with the same rules
SEGMENTS = [
    {'key': 'mobile-users',
     'name': 'Mobile Users',
     'description': 'Users who have accessed the application via mobile device',
     'environments': ['test', 'production', 'template-env'],
     'rules': [['device', 'platform', 'in', ['Mobile']]]},
    {'key': 'development-team',
     'name': 'Development Team',
     'description': 'Users who are part of the development team',
     'environments': ['test', 'production', 'template-env'],
     'rules': [['user', 'role', 'in', ['Developer']]]},
    {'key': 'launch-airways-all-members',
     'name': 'Launch Airways All Members',
     'description': 'Users who are part of the LaunchAirways Club Membership',
     'environments': ['test', 'production', 'template-env'],
     'rules': [['user', 'launchclub', 'in', ['standard', 'platinum']]]},
    {'key': 'launch-airways-platinum-members',
     'name': 'Launch Airways Platinum Members',
     'description': 'Users who are part of the LaunchAirways Club Membership',
     'environments': ['test', 'production', 'template-env'],
     'rules': [['user', 'launchclub', 'in', ['platinum']]]},
    {'key': 'beta-users',
     'name': 'Beta Users',
     'description': 'Users who are part of the beta program',
     'environments': ['test', 'production', 'template-env'],
     'rules': [['user', 'role', 'in', ['Beta']]]},
    {'key': 'blocked-users',
     'name': 'Blocked Users',
     'description': 'Users blocked by guardrails due to unsafe prompts',
     'environments': ['test', 'production', 'template-env'],
     'rules': [['user', 'key', 'in', ['']]]},
    {'custom': 'segment_ai_fallback'},
]

# Context kinds — [key, for_experiment]
CONTEXT_KINDS = [
    ['audience', True],
    ['location', True],
    ['device', True],
    ['experience', True],
]

# Experiments — toggled flag, metrics, and create_experiment kwargs
EXPERIMENTS = [
    {'requires': 'metric_groups_created',
     'toggle_flag': ['storeAttentionCallout', 'on', 'production', 'Turn on flag for experiment'],
     'metrics': [['store-purchases', True], ['in-cart-total-price', False]],
     'experiment': {'exp_key': 'new-collection-promotion-banner',
                    'exp_name': '(Bayesian) Funnel Experiment: New Collection Promotion Banner',
                    'exp_env': 'production',
                    'flag_key': 'storeAttentionCallout',
                    'hypothesis': 'If we adjust the header text to better copy we can drive '
                                  'greater attention into the stores in question, and greater '
                                  'conversion of checkout activities.',
                    'primary_key': 'store-purchases',
                    'attributes': ['device', 'location', 'tier', 'operating_system'],
                    'flagConfigVersion': 2},
     'start_iteration': False},
    {'requires': 'metrics_created',
     'toggle_flag': ['cartSuggestedItems', 'on', 'production', 'Turn on flag for experiment'],
     'metrics': [['in-cart-total-items', False], ['in-cart-total-price', False]],
     'experiment': {'exp_key': 'suggested-items-carousel',
                    'exp_name': '(Bayesian) Feature Experiment: Suggested Items Carousel',
                    'exp_env': 'production',
                    'flag_key': 'cartSuggestedItems',
                    'hypothesis': 'If we enable the new cart suggested items feature, we can drive '
                                  'greater upsell conversion.',
                    'primary_key': 'in-cart-total-items',
                    'attributes': ['device', 'location', 'tier', 'operating_system'],
                    'flagConfigVersion': 2},
     'start_iteration': False},
    {'requires': 'metric_groups_created',
     'toggle_flag': ['release-new-shorten-collections-page',
                     'on',
                     'production',
                     'Turn on flag for experiment'],
     'metrics': [['shorten-collection-page-metric-group', True], ['in-cart-total-price', False]],
     'experiment': {'exp_key': 'new-shorten-collection-pages',
                    'exp_name': '(Frequentist) Funnel Experiment: New Shorten Collection Pages',
                    'exp_env': 'production',
                    'flag_key': 'release-new-shorten-collections-page',
                    'hypothesis': 'We would want to reduce the collection page to the top three '
                                  'items to reduce customer decision fatigue in order to increase '
                                  'checkout and overall revenue.',
                    'primary_key': 'shorten-collection-page-metric-group',
                    'methodology': 'frequentist',
                    'analysisConfig': {'significanceThreshold': '5', 'testDirection': 'two-sided'},
                    'attributes': ['device', 'location', 'tier', 'operating_system'],
                    'flagConfigVersion': 2},
     'start_iteration': True},
    {'requires': 'metrics_created',
     'toggle_flag': ['release-new-search-engine',
                     'on',
                     'production',
                     'Turn on flag for experiment'],
     'metrics': [['search-engine-add-to-cart', False], ['in-cart-total-price', False]],
     'experiment': {'exp_key': 'new-search-engine',
                    'exp_name': '(Frequentist) Feature Experiment: New Search Engine',
                    'exp_env': 'production',
                    'flag_key': 'release-new-search-engine',
                    'hypothesis': 'We want to a new search engine that is more ranks search '
                                  'results diffrently and have an Add To Cart button built inside '
                                  'the component in order to increase ease of adding items to cart '
                                  'and increasing revenue.',
                    'primary_key': 'search-engine-add-to-cart',
                    'methodology': 'frequentist',
                    'analysisConfig': {'significanceThreshold': '5', 'testDirection': 'two-sided'},
                    'attributes': ['device', 'location', 'tier', 'operating_system'],
                    'flagConfigVersion': 2},
     'start_iteration': True},
    {'requires': 'metrics_created',
     'toggle_flag': ['ai-config--togglebot', 'on', 'production', 'Turn on flag for experiment'],
     'metrics': [['ai-accuracy', False],
                 ['ai-source-fidelity', False],
                 ['ai-relevance', False],
                 ['ai-cost', False],
                 ['ai-chatbot-negative-feedback', False]],
     'experiment': {'exp_key': 'hallucination-detection-experiment',
                    'exp_name': 'Hallucination Detection: AI Model Performance Evaluation',
                    'exp_env': 'production',
                    'flag_key': 'ai-config--togglebot',
                    'hypothesis': 'This experiment evaluates different AI models for their '
                                  'performance in preventing hallucinations and maintaining '
                                  'response quality. We measure accuracy, source fidelity, '
                                  'relevance, cost efficiency, and user feedback to determine '
                                  'which model configuration provides the most reliable and '
                                  'trustworthy responses while maintaining cost effectiveness.',
                    'primary_key': 'ai-accuracy',
                    'attributes': ['device', 'location', 'tier', 'operating_system'],
                    'flagConfigVersion': 2},
     'start_iteration': True},
    {'requires': 'metrics_created',
     'toggle_flag': None,
     'metrics': [['ai-accuracy', False],
                 ['ai-source-fidelity', False],
                 ['ai-relevance', False],
                 ['ai-cost', False],
                 ['ai-chatbot-negative-feedback', False]],
     'experiment': {'exp_key': 'brand-voice-model-comparison',
                    'exp_name': 'Brand Voice Model Comparison: Multi-Agent Prompt Impact',
                    'exp_env': 'production',
                    'flag_key': 'ai-config--togglebot-brand-voice',
                    'hypothesis': 'This experiment compares four AI models (Nova Pro, Haiku, GPT-5 '
                                  'Mini, Sonnet 4.6) powering the Brand Voice agent in our '
                                  'multi-agent pipeline. We measure accuracy, source fidelity, '
                                  'relevance, cost, and user feedback to determine which model '
                                  'delivers the best brand-consistent responses while balancing '
                                  'quality and cost.',
                    'primary_key': 'ai-accuracy',
                    'attributes': ['device', 'location', 'tier', 'operating_system'],
                    'flagConfigVersion': 2},
     'start_iteration': True},
    {'requires': 'metric_groups_created',
     'toggle_flag': ['releaseNewSignupPromo', 'on', 'production', 'Turn on flag for experiment'],
     'metrics': [['togglebank-signup-funnel', True]],
     'experiment': {'exp_key': 'togglebank-signup-funnel-experiment',
                    'exp_name': '(Bayesian) Funnel Experiment: ToggleBank Multi-Step Signup Flow',
                    'exp_env': 'production',
                    'flag_key': 'releaseNewSignupPromo',
                    'hypothesis': 'Testing which marketing banner offer (credit card, mortgage, or '
                                  'cashback) drives the most signup conversions in ToggleBank.',
                    'primary_key': 'togglebank-signup-funnel',
                    'attributes': ['device', 'location', 'tier', 'operating_system'],
                    'flagConfigVersion': 2},
     'start_iteration': True},
    {'requires': 'metrics_created',
     'toggle_flag': ['showDifferentSpecialOfferString',
                     'on',
                     'production',
                     'Turn on flag for experiment'],
     'metrics': [['signup-started', False]],
     'experiment': {'exp_key': 'togglebank-special-offers-experiment',
                    'exp_name': '(Bayesian) Feature Experiment: ToggleBank Special Offers Rotation',
                    'exp_env': 'production',
                    'flag_key': 'showDifferentSpecialOfferString',
                    'hypothesis': 'Testing which special offer variation (credit card, car loan, '
                                  'or platinum rewards) generates more signup conversions.',
                    'primary_key': 'signup-started',
                    'attributes': ['device', 'location', 'tier', 'operating_system'],
                    'flagConfigVersion': 2},
     'start_iteration': True},
    {'requires': 'metrics_created',
     'toggle_flag': ['swapWidgetPositions', 'on', 'production', 'Turn on flag for experiment'],
     'metrics': [['signup-started', False]],
     'experiment': {'exp_key': 'togglebank-widget-position-experiment',
                    'exp_name': '(Bayesian) Feature Experiment: ToggleBank Widget Position Swap',
                    'exp_env': 'production',
                    'flag_key': 'swapWidgetPositions',
                    'hypothesis': 'Testing whether swapping the positions of mortgage and '
                                  'retirement widgets improves signup conversion rates.',
                    'primary_key': 'signup-started',
                    'attributes': ['device', 'location', 'tier', 'operating_system'],
                    'flagConfigVersion': 2},
     'start_iteration': True},
    {'requires': 'metrics_created',
     'toggle_flag': ['ai-config--publicbot', 'on', 'production', 'Turn on flag for experiment'],
     'metrics': [['ai-chatbot-positive-feedback', False], ['ai-chatbot-negative-feedback', False]],
     'experiment': {'exp_key': 'government-ai-config-experiment',
                    'exp_name': 'AI Config: PublicBot Experiment - Public Sector',
                    'exp_env': 'production',
                    'flag_key': 'ai-config--publicbot',
                    'hypothesis': 'Which AI Models are providing best experiences to users and '
                                  'delivering best responses for government services',
                    'primary_key': 'ai-chatbot-positive-feedback',
                    'attributes': ['device', 'location', 'tier', 'operating_system'],
                    'flagConfigVersion': 1},
     'start_iteration': True},
    {'requires': 'metrics_created',
     'toggle_flag': ['showHeroRedesign', 'on', 'production', 'Turn on flag for experiment'],
     'metrics': [['signup-clicked', False]],
     'experiment': {'exp_key': 'government-hero-redesign',
                    'exp_name': '(Bayesian) Feature Experiment: Show Hero Redesign',
                    'exp_env': 'production',
                    'flag_key': 'showHeroRedesign',
                    'hypothesis': 'Testing whether the new hero design leads to increased signup '
                                  'conversion on the government demo page',
                    'primary_key': 'signup-clicked',
                    'attributes': ['device', 'location', 'tier', 'operating_system'],
                    'flagConfigVersion': 2},
     'start_iteration': True},
    {'requires': 'metrics_created',
     'toggle_flag': ['showDifferentHeroImageString',
                     'on',
                     'production',
                     'Turn on flag for experiment'],
     'metrics': [['signup-clicked', False]],
     'experiment': {'exp_key': 'government-show-different-hero-image',
                    'exp_name': '(Frequentist) Feature Experiment: Show Different Hero Image',
                    'exp_env': 'production',
                    'flag_key': 'showDifferentHeroImageString',
                    'hypothesis': 'Testing different hero images to see which leads to increased '
                                  'signup conversion on the government demo page',
                    'primary_key': 'signup-clicked',
                    'methodology': 'frequentist',
                    'analysisConfig': {'significanceThreshold': '5', 'testDirection': 'two-sided'},
                    'attributes': ['device', 'location', 'tier', 'operating_system'],
                    'flagConfigVersion': 2},
     'start_iteration': True},
]

# Release-pipeline rollouts — flag additions, metric attachments, phase advances
PIPELINE_FLAGS = [
    {'flag_key': 'enhancedUserAuthentication', 'pipeline_key': 'togglebank-v2-pipeline'},
    {'flag_key': 'biometricLoginSupport', 'pipeline_key': 'togglebank-v2-pipeline'},
    {'flag_key': 'customizableAccountDashboards', 'pipeline_key': 'togglebank-v2-pipeline'},
    {'flag_key': 'realTimeTransactionAlerts', 'pipeline_key': 'togglebank-v2-pipeline'},
    {'flag_key': 'aiPoweredExpenseCategorization', 'pipeline_key': 'togglebank-v2-pipeline'},
    {'flag_key': 'fraudDetectionAlerts', 'pipeline_key': 'togglebank-v2-pipeline'},
    {'flag_key': 'darkModeInterfaceOption', 'pipeline_key': 'togglebank-v2-pipeline'},
    {'flag_key': 'automatedSavingsGoals',
     'pipeline_key': 'togglebank-v2-pipeline',
     'metrics': ['stocks-api-latency', 'stocks-api-error-rates'],
     'advance_phases': [['active', 'test', {}]]},
    {'flag_key': 'multiCurrencySupport',
     'pipeline_key': 'togglebank-v2-pipeline',
     'metrics': ['stocks-api-latency', 'stocks-api-error-rates'],
     'advance_phases': [['active', 'test', {}]]},
    {'flag_key': 'peerToPeerPaymentTransfers',
     'pipeline_key': 'togglebank-v2-pipeline',
     'metrics': ['stocks-api-latency', 'stocks-api-error-rates'],
     'advance_phases': [['active', 'test', {}]]},
    {'flag_key': 'creditScoreMonitoringTool',
     'pipeline_key': 'togglebank-v2-pipeline',
     'metrics': ['stocks-api-latency', 'stocks-api-error-rates'],
     'advance_phases': [['active', 'test', {}]]},
    {'flag_key': 'voiceCommandBankingAssistant',
     'pipeline_key': 'togglebank-v2-pipeline',
     'metrics': ['stocks-api-latency', 'stocks-api-error-rates'],
     'advance_phases': [['active', 'test', {}]]},
    {'flag_key': 'loanApplicationTracker',
     'pipeline_key': 'togglebank-v2-pipeline',
     'metrics': ['stocks-api-latency', 'stocks-api-error-rates'],
     'advance_phases': [['active', 'test', {}]]},
    {'flag_key': 'detailedSpendingInsightsReports',
     'pipeline_key': 'togglebank-v2-pipeline',
     'metrics': ['stocks-api-latency', 'stocks-api-error-rates'],
     'advance_phases': [['active', 'test', {}], ['active', 'guard', {}], ['active', 'ga', {}]]},
    {'flag_key': 'scheduledBillPayments',
     'pipeline_key': 'togglebank-v2-pipeline',
     'metrics': ['stocks-api-latency', 'stocks-api-error-rates'],
     'advance_phases': [['active', 'test', {}], ['active', 'guard', {}], ['active', 'ga', {}]]},
    {'flag_key': 'crossBorderPaymentSimplification',
     'pipeline_key': 'togglebank-v2-pipeline',
     'metrics': ['stocks-api-latency', 'stocks-api-error-rates'],
     'advance_phases': [['active', 'test', {}], ['active', 'guard', {}]]},
    {'flag_key': 'merchantRewardsIntegration',
     'pipeline_key': 'togglebank-v2-pipeline',
     'metrics': ['stocks-api-latency', 'stocks-api-error-rates'],
     'advance_phases': [['active', 'test', {}], ['active', 'guard', {}]]},
    {'flag_key': 'virtualCardIssuance',
     'pipeline_key': 'togglebank-v2-pipeline',
     'metrics': ['stocks-api-latency', 'stocks-api-error-rates'],
     'advance_phases': [['active', 'test', {}], ['active', 'guard', {}], ['active', 'ga', {}]]},
    {'flag_key': 'apiSupportForThirdPartyApplications',
     'pipeline_key': 'togglebank-v2-pipeline',
     'metrics': ['stocks-api-latency', 'stocks-api-error-rates'],
     'advance_phases': [['active', 'test', {}], ['active', 'guard', {}], ['active', 'ga', {}]]},
]
