import { BankingDataInterface } from "@/utils/apiTypesInterface";
export const creditData: BankingDataInterface[] = [
  {
    id: 1,
    date: "2023-01-03",
    merchant: "Pharmacy",
    amount: "265.73",
    status: "successful",
    accounttype: "credit",
    user: "Default",
  },
  {
    id: 2,
    date: "2023-10-17",
    merchant: "GasStation",
    amount: "83.59",
    status: "successful",
    accounttype: "credit",
    user: "Default",
  },
  {
    id: 3,
    date: "2023-05-01",
    merchant: "Restaurant",
    amount: "33.91",
    status: "successful",
    accounttype: "credit",
    user: "Default",
  },
  {
    id: 4,
    date: "2023-01-18",
    merchant: "Pharmacy",
    amount: "153.54",
    status: "successful",
    accounttype: "credit",
    user: "Default",
  },
  {
    id: 5,
    date: "2023-07-11",
    merchant: "TechStore",
    amount: "26.06",
    status: "pending",
    accounttype: "credit",
    user: "Default",
  },
  {
    id: 6,
    date: "2023-05-26",
    merchant: "OnlineMarket",
    amount: "219.07",
    status: "pending",
    accounttype: "credit",
    user: "Default",
  },
];
