import { BankingDataInterface } from "@/utils/apiTypesInterface";

export const newCheckingData: BankingDataInterface[] = [
  {
    id: 1,
    date: "2023-07-24",
    merchant: "SuperMarket",
    amount: "336.55",
    status: "successful",
    accounttype: "checking",
    user: "Default",
  },
  {
    id: 2,
    date: "2023-06-01",
    merchant: "Pharmacy",
    amount: "13.32",
    status: "successful",
    accounttype: "checking",
    user: "Default",
  },
  {
    id: 3,
    date: "2023-03-23",
    merchant: "TechStore",
    amount: "188.35",
    status: "successful",
    accounttype: "checking",
    user: "Default",
  },
  {
    id: 4,
    date: "2023-09-15",
    merchant: "BookStore",
    amount: "221.99",
    status: "pending",
    accounttype: "checking",
    user: "Default",
  },
  {
    id: 5,
    date: "2023-06-05",
    merchant: "TechStore",
    amount: "105.25",
    status: "successful",
    accounttype: "checking",
    user: "Default",
  },
  {
    id: 6,
    date: "2023-09-17",
    merchant: "OnlineMarket",
    amount: "283.56",
    status: "pending",
    accounttype: "checking",
    user: "Default",
  },
  {
    id: 7,
    date: "2023-05-01",
    merchant: "GasStation",
    amount: "347.89",
    status: "successful",
    accounttype: "checking",
    user: "Default",
  },
  {
    id: 8,
    date: "2023-10-05",
    merchant: "SuperMarket",
    amount: "242.05",
    status: "successful",
    accounttype: "checking",
    user: "Default",
  },
  {
    id: 9,
    date: "2023-06-26",
    merchant: "Pharmacy",
    amount: "113.46",
    status: "pending",
    accounttype: "checking",
    user: "Default",
  },
  {
    id: 10,
    date: "2023-03-06",
    merchant: "CoffeeShop",
    amount: "249.67",
    status: "successful",
    accounttype: "checking",
    user: "Default",
  },
  {
    id: 11,
    date: "2023-09-01",
    merchant: "PetShop",
    amount: "324.77",
    status: "successful",
    accounttype: "checking",
    user: "Default",
  },
  {
    id: 12,
    date: "2023-01-22",
    merchant: "GasStation",
    amount: "373.07",
    status: "successful",
    accounttype: "checking",
    user: "Default",
  },
  {
    id: 13,
    date: "2023-01-21",
    merchant: "OnlineMarket",
    amount: "201.22",
    status: "successful",
    accounttype: "checking",
    user: "Default",
  },
  {
    id: 14,
    date: "2023-03-31",
    merchant: "TechStore",
    amount: "494.49",
    status: "pending",
    accounttype: "checking",
    user: "Default",
  },
  {
    id: 15,
    date: "2023-09-06",
    merchant: "GasStation",
    amount: "421.14",
    status: "successful",
    accounttype: "checking",
    user: "Default",
  },
  {
    id: 16,
    date: "2023-05-14",
    merchant: "SuperMarket",
    amount: "360.16",
    status: "successful",
    accounttype: "checking",
    user: "Default",
  },
  {
    id: 17,
    date: "2023-04-16",
    merchant: "SuperMarket",
    amount: "493.93",
    status: "pending",
    accounttype: "checking",
    user: "Default",
  },
  {
    id: 18,
    date: "2023-03-09",
    merchant: "OnlineMarket",
    amount: "21.79",
    status: "pending",
    accounttype: "checking",
    user: "Default",
  },
  {
    id: 19,
    date: "2023-10-24",
    merchant: "Restaurant",
    amount: "170.50",
    status: "successful",
    accounttype: "checking",
    user: "Default",
  },
  {
    id: 20,
    date: "2023-02-26",
    merchant: "OnlineMarket",
    amount: "111.05",
    status: "successful",
    accounttype: "checking",
    user: "Default",
  },
];
