import { BankingDataInterface } from "@/utils/apiTypesInterface";
export const oldCheckingData: BankingDataInterface[] = [
  {
    id: 1,
    date: "2023-07-24",
    merchant: "SuperMarket",
    amount: "336.55",
    status: "successful",
    accounttype: "checking",
    user: "Default",
  },
  {
    id: 2,
    date: "2023-06-01",
    merchant: "Pharmacy",
    amount: "13.32",
    status: "successful",
    accounttype: "checking",
    user: "Default",
  },
  {
    id: 3,
    date: "2023-03-23",
    merchant: "TechStore",
    amount: "188.35",
    status: "successful",
    accounttype: "checking",
    user: "Default",
  },
  {
    id: 4,
    date: "2023-09-15",
    merchant: "BookStore",
    amount: "221.99",
    status: "pending",
    accounttype: "checking",
    user: "Default",
  },
  {
    id: 5,
    date: "2023-06-05",
    merchant: "TechStore",
    amount: "105.25",
    status: "successful",
    accounttype: "checking",
    user: "Default",
  },
  {
    id: 6,
    date: "2023-09-17",
    merchant: "OnlineMarket",
    amount: "283.56",
    status: "pending",
    accounttype: "checking",
    user: "Default",
  },
  {
    id: 7,
    date: "2023-05-01",
    merchant: "GasStation",
    amount: "347.89",
    status: "successful",
    accounttype: "checking",
    user: "Default",
  },
  {
    id: 8,
    date: "2023-10-05",
    merchant: "SuperMarket",
    amount: "242.05",
    status: "successful",
    accounttype: "checking",
    user: "Default",
  },
];
