name: 'Image Deployment on EKS' 

on:
  push:
    branches:
      - deploy_images_to_k8s

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1
  KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
  KUBE_NAMESPACE: $!
  ECR_REPOSITORY: ld-core-demo
  KUBECTL_VERSION: "v1.23.0"
  LD_API_KEY: ${{ secrets.LD_API_KEY }}


jobs:
  deploy-to-pods:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        environment: [1, 2 , 3 , 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./.github/workflows/requirements.txt

    - name: Get LD ENVs
      id: get-envs
      run: |
        echo "var1=$(python ./.github/workflows/get_ld_values.py | sed -n '1p')" >> $GITHUB_ENV
        echo "var2=$(python ./.github/workflows/get_ld_values.py | sed -n '2p')" >> $GITHUB_ENV
      env:
        LD_ENV_KEY: demo-${{ matrix.environment }}
        LD_API_KEY: ${{ secrets.LD_API_KEY }}

    - name: Create .env file
      run: |
        touch ./.env
        echo NEXT_PUBLIC_LD_CLIENT_KEY=${{ env.var1 }} >> ./.env
        echo LD_SDK_KEY=${{ env.var2 }} >> ./.env
        echo DB_URL=postgresql://postgres:LDD3v3xp@fielddemodb.cii3vie7naoe.us-west-2.rds.amazonaws.com:5432 >> ./.env

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ld-core-demo
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:ld-demo${{ matrix.environment }}-${{ github.run_number }} .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:ld-demo${{ matrix.environment }}-${{ github.run_number }}

    - name: Update K8s Deploy File
      run: python ./.github/workflows/update_k8s_deploy.py
      env:
        NAMESPACE: demo${{ matrix.environment }}
        IMAGE_TAG: ld-demo${{ matrix.environment }}-${{ github.run_number }}

    - name: Check Deploy file
      run: cat ./.github/workflows/deploy_files/deploy.yaml
    
    - name: Applying deploy file to Kubernetes
      uses: kodermax/kubectl-aws-eks@master
      with:
        args: apply -f ./.github/workflows/deploy_files/deploy.yaml -n demo${{ matrix.environment }}

    - name: Restart pods
      uses: kodermax/kubectl-aws-eks@master
      with:
        args: rollout restart deployment/ld-core-demo-deployment -n demo${{ matrix.environment }}

   
    - name: Delete the deploy file
      run: rm -rf ./.github/workflows/deploy_files

    - name: Remove .env file
      run: rm ./.env